name: eCommerce Actions
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: action/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-vetrion: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm build
      - name: linter check
        run: npm check
      - name: linter fix
        run: npm fix
      - name: unit test
        run: npm test
